GET http://localhost:3010/

###
GET http://localhost:3010/tweets

###
POST http://localhost:3010/
Content-Type: application/json

{
    "username": "einarlop",
    "tweet": "test"
}

###
GET http://localhost:3010/tweets/einarlop
